name: skeletonx
description: A SkeletonX project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  falconx:
    path: ./packages/falconx

  http: ^0.13.5

  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.1
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  widgetbook: ^3.0.0-beta.13


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/
    - assets/font/
    - assets/icon/
    - assets/mock/
    - assets/image/
    - assets/image/2.0x/
    - assets/image/3.0x/
    - assets/launcher/
    - assets/launcher/dev/
    - assets/launcher/uat/

  fonts:
    - family: Thai
      fonts:
        - asset: assets/font/anuphan_regular.otf
          weight: 400
        - asset: assets/font/anuphan_medium.otf
          weight: 500
        - asset: assets/font/anuphan_semibold.otf
          weight: 600
        - asset: assets/font/anuphan_bold.otf
          weight: 700
    - family: English
      fonts:
        - asset: assets/font/inter_regular.otf
          weight: 400
        - asset: assets/font/inter_medium.otf
          weight: 500
        - asset: assets/font/inter_semibold.otf
          weight: 600
        - asset: assets/font/inter_bold.otf
          weight: 700